name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        node-version: [20.x]

    name: Create a new release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

        # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies with pnpm
      - name: Install dependencies
        run: pnpm install

      # Disable Husky for CI (optional)
      - name: Disable Husky
        run: export HUSKY=0

      # Run semantic-release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Upload coverage reports to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
